print("=========Desafio 02=========")
print("-----DATA DO SEU ANIVERSÁRIO-----")
dia = int(input("\tDia = "))
mes = input("\tMês = ")
ano = int(input("\tAno = "))
print(f"Você nasceu no dia {dia}", end='')
print(f" de {mes} de {ano}, correto?")